### ISSUE TITLE
TRACKER: Record demonstrations

### ISSUE THREAD

**Issue by fire** [V-Sekai/V-Sekai.github.io#262]
Record at 3840 x 2160 pixels (4K UHD) for both video and images.

Video will have a safety crop.

- [ ] Demo the the launch of the godot editor.
- [ ] Demo avatar upload
- [ ] Demo itch
- [ ] Demo build systems
- [ ] Demo uro system
- [ ] Demo regular desktop game locomotion
- [ ] Demo avatar loading
- [ ] Demo multiple players
- [ ] Demo server load and execute

**Comment by fire** [comment]
We're able to import some level artwork.

Task to investigate why sdfgi isn't working in clustered forward vulkan render.

**Comment by fire** [comment]
We decided on the tasks and have split the tasks so they can be tracked separately.
