### ISSUE TITLE
Describe a possible roadmap

### ISSUE THREAD

**Issue by fire** [V-Sekai/V-Sekai.github.io#435]
### Metadata

- Status: proposed 
- Deciders: V-Sekai,
- Tags: V-Sekai,

### Context and Problem Statement

We need to choose features to add to V-Sekai.

### Describe the proposed option and how it helps to overcome the problem or limitation

Trim the steps needed to create the game.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

Main development:

- [ ]  Develop prototype of in-game tablet interface (L)
  - [ ] Implement features to place objects (M)
  - [ ] Debug color picker (S)

Future development:

- [ ] Debug joining separate worlds with different steps (L)
- [ ] Refine UI and user experience (L)
  - [ ] Test and debug prototype (L)
- [ ] Debug backend upload support (L)
- [ ] Debug backend server lobby (L)
- [ ] Debug engine multiplayer (L)
- [ ] Define architecture and create design document (S)
- [ ] Implement text input (S)
- [ ] Adjust objects with PLY (M)
- [ ] Integrate the PLY addon for manifold meshes (L)
- [ ] Implement features to lock objects (M)
- [ ] Debug VOIP chat (M)
- [ ] Merge, subtract and intersect 3D models (XL)
- [ ] Focus a group of 3d models M)
- [ ] Tools with sliders (M)
  - [ ] Adjust constraints of the tool sliders with dag adjustment.

### Positive Consequences

We are able to use V-Sekai for fun and work.

### Negative Consequences

We cannot get other features in.

### Option graveyard

- Option: The status quo. 
- Rejection Reason: This solves nothing. 

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Knowing what to do is hard.

### Is there a reason why this should be core and done by us?

This is a list of core features.

### References

- [V-Sekai](https://v-sekai.org/)

**Comment by fire** [comment]
Posted to dd96967c97b5ff733509451367a8b89eaf9f6814.
